### ISSUE TITLE
[Feature suggestion] Option to swap behaviour on ctrl and alt #4

### ISSUE THREAD

**Issue by akrigline** [itamarcu/ZoomPanOptions#1]
> Ctrl+scroll to zoom is pretty common behaviour in a lot of apps. Having MW to pan, ctrl+MW to zoom (and then shift/alt+MW for rotation) would let Foundry match that. Could be a toggle in the module options, rather than a default setting.
> 
> (Also, I am super happy that this supports sideways scrolling!)

From @BadIdeasBureau on [CanvasScroll #4](https://github.com/ElfFriend-DnD/foundryvtt-canvasScroll/issues/4)

**Comment by akrigline** [comment]
#3 makes Ctrl the default zoom key, unlike how I had it in CanvasScroll. But the idea to allow users to set this is still a good idea, and some of the changes in that PR will facilitate this.

**Comment by itamarcu** [comment]
For now, I'm making multiple modes (see readme). More modes can be added or even split into multiple settings but for now I tried to keep it simple, avoid overriding alt behavior, and keep allowing all existing features.
