### ISSUE TITLE
Add ability to change minimum and maximum zoom levels

### ISSUE THREAD

**Issue by geoidesic** [itamarcu/ZoomPanOptions#11]
I notice in your code: `const max = CONFIG.Canvas.maxZoom`
Would be good if we could set this in settings and ideally globally not per-player... or better yet it should be per scene? Or maybe a global setting and a per scene adjustment would be ideal.

The reason this is useful is for very large maps. E.g. I've put Waterdeep in as a map on Roll20 and it handles it fine. Yes it's a big file but once it's loaded you can zoom all the way in and out with ease. On the Foundry it's not usable because of max zoom.

**Comment by itamarcu** [comment]
Would be a neat little feature that shouldn't be hard to add. I'd prefer not to add too many settings to the settings page, but this one feels reasonable and I've already [seen someone else ask for it in the discord](https://discordapp.com/channels/170995199584108546/713259405667205193/759683387455045673).

I might add a setting to change minimum zoom too.

**Comment by itamarcu** [comment]
Added in v1.4.0!
