### ISSUE TITLE
BUG: Breaks when rotating token too fast

### ISSUE THREAD

**Issue by GambetTV** [itamarcu/ZoomPanOptions#17]
This is a problem when combining this module with the module "About Face". Scrolling too fast (basically faster than a snail's pace) to change direction of a token causes the token to freak out and start dancing or something (it basically rotates 30 degrees back and forth endlessly) causing the whole game to lag out until you refresh.

**Comment by itamarcu** [comment]
Fixed in 1.5.0, hopefully.  If not, please reopen this ticket!
