### ISSUE TITLE
Rotating spell templates stalls the Foundry server

### ISSUE THREAD

**Issue by Akaito** [itamarcu/ZoomPanOptions#18]
Similar to "BUG: Breaks when rotating token too fast #17".

If I rotate a placed template using shift + mouse wheel too far, regardless of how quickly I'm doing it, zoom/pan options will stall the Foundry server.  Sometimes it recovers after a delay.  Sometimes I have to manually restart the Foundry process.

I narrowed this down to absolutely being within Zoom/Pan Options by disabling modules until I could get to the minimal set that caused this.  This is occurring in module version 1.4.0.  I'm uncertain if this is new to this specific version, but I know I didn't used to have this problem some weeks ago.

**Comment by itamarcu** [comment]
Well that's very concerning!  I can't manage to reproduce it, though.

Could you share your options for this module?

i.e. this page:

![image](https://user-images.githubusercontent.com/6516621/106665612-35217780-65af-11eb-8483-7ce13a7269f4.png)

Also - what is your browser, your foundry version, and does this happen even with no other modules running?

**Comment by Akaito** [comment]
Screenshot taken while I have my normal modules enabled, but I did confirm this happened with as little as Zoom/Pan Options and "Tidy UI - Game Settings".  I've also now seen it from Firefox on Windows 10, and Firefox on Linux Mint.

I'll email you a URL and user/password for a guest player to see if it repros for you there.  This is on a server that runs 24/7, though I do occasionally back out of the world to update modules, etc.

![2021-02-03_17-07-46](https://user-images.githubusercontent.com/6599279/106830201-72831500-6642-11eb-99f4-5a4fa18fed8a.png)

**Comment by itamarcu** [comment]
Fixed, in 1.5.0, hopefully.  If not, reopen the ticket.  Thanks a lot for giving me access to your server to help debug it, even though at the end I think I found the problem just by looking at the code differences (Foundry has added some code to rate-limit rotations).

**Comment by Akaito** [comment]
Confirmed the fix in 1.5.0!  Thanks much!  :)
