### ISSUE TITLE
Mousewheel rotates selected tokens instead of zooming

### ISSUE THREAD

**Issue by MachDelta** [itamarcu/ZoomPanOptions#19]
I just installed this module, and the mousewheel rotates all selected tokens (without Shift or Ctrl held) instead of zooming in and out as expected. To zoom in/out you have to have no token selected.
Basically, it seems to behave as though the Ctrl key is always being held.

Tested with Chrome, Firefox, and Foundry's built-in client, in a world with no other modules installed.

**Comment by itamarcu** [comment]
yikes.  my bad.  thanks for reporting this.

fixing this now, in version 1.5.1!
