### ISSUE TITLE
1.5.1 Breaks Zooming and Panning

### ISSUE THREAD

**Issue by DrWiFi** [itamarcu/ZoomPanOptions#20]
Hello,
The latest update made the module non-functional. No matter what options are chosen only the default foundry zoom/pan functions work.
Rolling back to 1.5.0 restores functionality. 
OS: Mac OS X
Browser: Chrome
Foundry 0.7.9
D&D: 1.2.4
Thanks

**Comment by Akmenus** [comment]
Here too. Last update broken zoom.

Windows 10
Execute in .exe
Foundry 0.7.9
Simple World Building

**Comment by Geodragon9** [comment]
Same, updated, then noticed mouse wheel for zooming stopped working.  I had to kill the module so that I can use the mouse wheel to zoom.

**Comment by Brimcon** [comment]
The mousewheel scroll only works when you have a token selected.

**Comment by itamarcu** [comment]
fuck.  totally my bad for not testing my fix enough.

try v1.5.2!
