### ISSUE TITLE
Mousewheel longer works since latest update

### ISSUE THREAD

**Issue by halfwalk** [itamarcu/ZoomPanOptions#21]
The mouse wheel no longer zooms with this module enabled, regardless of which settings I choose. As far as I can tell, the module appears to be broken now.

Tried on Chrome and Opera, Windows 10, hosting on The Forge. Foundry 0.7.9. Zoom/Pan version 1.5.2

Tried with this as the only active module as a sanity check, same results.

**Comment by itamarcu** [comment]
fixed in 1.5.3 (big whoops, sorry)
