### ISSUE TITLE
token spins

### ISSUE THREAD

**Issue by markflo765** [itamarcu/ZoomPanOptions#22]
Hello,

Not sure if this is a new issue but my players were mentioning that when their token is selected and the scroll wheel is turned, instead of panning it spins the token direction. Is this intentional or a bug?

Running Foundry 0.7.9 and latest PF2e game system. Disabled all modules except ZoomPan so I know this is the source of the behavior.

Thank you

**Comment by itamarcu** [comment]
Which version of Zoom/Pan Options are you using?  I can't manage to reproduce this, but this was a bug recently.

Tokens should only be rotated if the user is scrolling while holding Ctrl/Shift.

**Comment by markflo765** [comment]
Hello, the version I had installed was 1.5.0. Just updated to 1.5.3 and the problem is solved. Thank you!

 

Mark
