### ISSUE TITLE
Breaks tile rotation

### ISSUE THREAD

**Issue by geoidesic** [itamarcu/ZoomPanOptions#23]
The normal shortcut for rotating a tile is to select the tile, then hold CTRL+SHIFT while using the scroll-wheel.
If I'm using touchpad mode for zoom / pan, then trying to rotate a tile causes hundreds of `Required field rotation not present in tile` errors.

**Comment by focalmatter** [comment]
Just to chime in, issue is also happening to me on 0.7.9

This exact error message pops up when I attempt to rotate a token or tile with the touchpad swipe or mousewheel scroll. Interestingly enough, _my players_ don't seem to run into this issue.

This issue occurs even if Zoom/Pan is the only enabled module.

**Comment by itamarcu** [comment]
Oh cool, this is probably the same as #26 which I just fixed in v1.6.5.
