### ISSUE TITLE
Feature Request: Middle-click drag to pan

### ISSUE THREAD

**Issue by paullessing** [itamarcu/ZoomPanOptions#25]
I would like to use my middle mouse button to pan (the way that another VTT I used to use does).

I'm happy to work on creating a pull request; but before I do, I wanted to ask if a) you would consider accepting this as a feature, and b) if you know whether there is any reason this might not work (e.g. if Foundry is incompatible with middle mouse features)?

**Comment by itamarcu** [comment]
I'd certainly accept this as a pull request or might even do it myself!  it would need to be a new setting, probably.  And yeah, I think it's possible to do.

**Comment by paullessing** [comment]
Oh cool, if you want to do it yourself don't let me stop you! I just wanted to check it hadn't already been decided not to do it for some reason or other :)

**Comment by itamarcu** [comment]
@paullessing - Added in v1.6.0 :)

**Comment by paullessing** [comment]
Amazing, thank you!
