### ISSUE TITLE
Default mode is impossible to use with a TouchPad in v1.6.2

### ISSUE THREAD

**Issue by mrkwnzl** [itamarcu/ZoomPanOptions#27]
Using macOS, the automatic detection of TouchPads breaks the default mode. I cannot simply zoom like I would in default Foundry because it also pans the canvas slightly and erratically switches between both modes. I attached a video where I simply tried to zoom out using the TouchPad in default mode. A Magic Mouse works slightly better, but has the same issue.

I’m not sure what the use case for that auto detection is, but on a mac, a setting to make that optional would be needed because otherwise the default mode is unusable.

Setup:

OS: macOS 14.1.1
Browser: Chrome
Foundry: v0.8.8
Zoom/Pan Options: 1.6.2

https://user-images.githubusercontent.com/40534855/124613088-2c411480-de73-11eb-901d-f2c13d4d6c7a.mov

**Comment by itamarcu** [comment]
Well drat, I guess I'll have to put the auto-detection behind a setting configuration after all.

**Comment by itamarcu** [comment]
@mrkwnzl Thanks for the speedy and detailed bug report.  I added another method of touchpad detection which was verified to work on my MacBook, and also added a "Default Mouse" setting in case it still causes issues.

Please update me on whether or not this new version works for you!

**Comment by mrkwnzl** [comment]
Hey! Sorry for the late response, my work was hectic last week. I can confirm that 1.6.5 works great. The auto detection fails occasionally, but not in a way that would disrupt the game too much. But the default mouse and touchpad modes work flawlessly. Thanks!
