### ISSUE TITLE
TokenData rotation "NaN"...

### ISSUE THREAD

**Issue by ksignorini** [itamarcu/ZoomPanOptions#29]
Zoom/Pan Options 1.6.3 and Foundry VTT 0.8.8 gives the following error when trying to rotate a token while on Touchpad mode:

TokenData rotation "NaN" is not a number between 0 and 360

![image](https://user-images.githubusercontent.com/6867660/124673072-73c8a000-de75-11eb-9406-59c1ad5c50d2.png)

**Comment by itamarcu** [comment]
I'm not able to replicate this - rotating tokens seems to be working fine for me, both with a mouse and with a MacBook touchpad.

Can you try doing this again and showing me your console logs? (F12, errors tab)

Also, let me know which OS and browser you're using, and how you're rotating the token (I assume it's with shift+scroll).

**Comment by ksignorini** [comment]
Turns out it's only Firefox. I just tested in Chrome and it works fine in Chrome.

I'll get you Firefox logs soon.

**Comment by ksignorini** [comment]
Here is Firefox console log as the error occurs:

`Error: [QacDbN796eyeaawK] TokenData rotation "NaN" is not a number between 0 and 360
    _validateField data.mjs:382
    validate data.mjs:273
    _preUpdateDocumentArray foundry.js:8766
    _updateEmbeddedDocuments foundry.js:8728
    update backend.mjs:153
    updateDocuments document.mjs:366
    updateEmbeddedDocuments document.mjs:532
    rotateMany foundry.js:19641
    _onMouseWheel foundry.js:20039
    _onWheel_Override zoom-pan-options.js:73
    <anonymous> zoom-pan-options.js:316
    call_wrapper libWrapper-wrapper.js:549
    0 libWrapper-wrapper.js:162
foundry.js:8769:17
Error: [QacDbN796eyeaawK] TokenData rotation "NaN" is not a number between 0 and 360
    _validateField data.mjs:382
    validate data.mjs:273
    _preUpdateDocumentArray foundry.js:8766
    _updateEmbeddedDocuments foundry.js:8728
    update backend.mjs:153
    updateDocuments document.mjs:366
    updateEmbeddedDocuments document.mjs:532
    rotateMany foundry.js:19641
    _onMouseWheel foundry.js:20039
    _onWheel_Override zoom-pan-options.js:73
    <anonymous> zoom-pan-options.js:316
    call_wrapper libWrapper-wrapper.js:549
    0 libWrapper-wrapper.js:162`

**Comment by itamarcu** [comment]
Cool, I found the problem, Firefox uses deltaY instead of wheelDelta.  Fixing in v1.6.5.

**Comment by ksignorini** [comment]
Fantastic! Thanks!
