### ISSUE TITLE
[Bug] scroll wheel pans up/down instead of zooming

### ISSUE THREAD

**Issue by tmcclintock** [itamarcu/ZoomPanOptions#32]
FVTT version 0.8.8
Game: Pathfinder 2nd Ed. v2.10.1.7007
ZoomPanOptions version: 1.6.5
Mouse: Logitec MX vertical mouse
OS: Windows 10
Hardware: Laptop w/ trackpad

Expected behavior: scrolling the mouse would result in zooming in/out (since I have ZPO set to "Default: standard behavior w/ auto detection for trackpads")

Actual: scrolling the mouse wheel pans the scene up/down.  Page up/down are not affected. Disabling ZPOptions restores the original behavior (but I love ZPO and want to keep it!).

**Comment by tmcclintock** [comment]
Update: changing to "Default: mouse ..." I got the expected behavior. Feel free to close this if you don't think it's an issue (I'd say it's a non-optimal default).

**Comment by itamarcu** [comment]
Also happened to me with a mouse connected to a Macbook.  I'll try to improve the auto detection.

**Comment by Weissrolf** [comment]
This happens for me on Windows using Chrome, but not using Firefox. I also noticed that when I use my usual Autohotkey scrippt for mouse-wheel input (it modifies it) then I get a mix of scrolling and zooming, but still more scrolling. Without my AHK script I get only scrolling. But again, only in Chrome, not in Firefox.

**Comment by itamarcu** [comment]
@Weissrolf - just to confirm, does this error disappear for you when the setting is set to "Default mouse" (no autodetection)?

**Comment by Weissrolf** [comment]
Yes, switching to "Default" without autodetection solves it on Chrome. No idea why Firefox isn't affected.

Chrome also behaves differently for zoom speed, though. I need higher numbers in FF compared to Chrome.  So both browsers seem to handle mouse-input differently to begin with.
