### ISSUE TITLE
Add support for changing the panning speed while dragging a token?

### ISSUE THREAD

**Issue by DelzounMora** [itamarcu/ZoomPanOptions#33]
When dragging a token to the edge of the screen, the panning speed is too fast to be usable. Do you think you could add functionality in your module to also edit this panning speed?

**Comment by itamarcu** [comment]
Currently when a selected token reaches the 50 screen pixels at any edge of the screen Foundry pans the window through `_onDragCanvasPan()`. This function moves the screen 50+ canvas pixels away over a duration of 200 milliseconds (more than 50 pixels the more zoomed out you are).

@DelzounMora What exactly feels "too fast" here?  Is it the 200ms number?  the 50 screen pixel pad that triggers it?  I'd appreciate it if you could explain the need in more detail or described the use case.

If you want, you can press F12, Ctrl+Shift+F, type `_onDragCanvasPan(event)`, click the source code place, and then try changing some numbers around and saving the file each time, to see how it affects the behavior.

**Comment by DelzounMora** [comment]
So the issue is the 50 pixel padding and the 3 tiles it moves. Lowering it down to 25 and 2 tiles made it work MUCH better. Thank you for the advice. Do you think it's going to be possible to add that as a feature to the module?

**Comment by itamarcu** [comment]
@DelzounMora I've added this feature in v1.7.0, allowing you to change these two specific numbers.
