### ISSUE TITLE
Foundry v9.232 breaks ZoomPanOptions

### ISSUE THREAD

**Issue by caewok** [itamarcu/ZoomPanOptions#35]
Foundry v9.232 (Testing 1) breaks ZoomPanOptions. Looks like it added a class `MouseManager` and moved the `_onWheel` method to that class. So wrapping `KeyboardManager.prototype._onWheel` no longer works and as a result, ZoomPanOptions will not load in v9.232.

**Comment by itamarcu** [comment]
Thanks so much for the contribution!
