### ISSUE TITLE
Should Alt be Token Rotation?

### ISSUE THREAD

**Issue by akrigline** [itamarcu/ZoomPanOptions#4]
Continuing the conversation from #3 here.

## The Problem:
With Touchpad mode the following keys have behaviors modified from foundry defaults:

- Shift + Scroll for horizontal canvas panning
- Ctrl + Scroll for zooming

This leaves the problem of where to put the keys that used to rotate tokens (Ctrl for 15deg, and Ctrl + Shift for 45deg).

## Current as of #3 Solution

Alt is what I picked in #3 as its currently only used to highlight tokens. Now in addition to highlighting tokens it replaces Ctrl while Touchpad mode is active.

- Alt for highlight all token/placeables
- Alt + Scroll rotate selected token/placeable 15deg
- Alt + Shift + Scroll rotate selected token/placeable 45deg

**Comment by akrigline** [comment]
Suggestion from @mrkwnzl:

> Shift + Alt + Scroll for rotating in 45°
> Ctrl + Alt + Scroll for rotating in 15°
> 
> This way, Alt is literally that: It alternates between the two use cases of rotating tokens and canvas navigation, but keeps the general buttons close to the Foundry default. And we can make it a choice (i.e., flip the possibilities from above): Holding Alt is either for controlling the rotation (that would be the default for the module and work like outlined above), or for controlling the canvas navigation (then the Foundry default for rotation would work, and Shift/Ctrl + Alt + Scroll pans horizontally/zooms).

I would need to test it, but I believe this has the same problem as only using the Alt key, which is that Foundry will still highlight all tokens when alt is pressed regardless of the combination of keys pressed. We could shim that, but doing so increases the surface areas of our changes.

**Comment by mrkwnzl** [comment]
> I would need to test it, but I believe this has the same problem as only using the Alt key, which is that Foundry will still highlight all tokens when alt is pressed regardless of the combination of keys pressed.

Yeah, my assumption for this proposed solution was that we can deactivate highlighting when pressed in a combination. If this can’t be changed or at too high a cost, another solution might be preferable.

**Comment by itamarcu** [comment]
Currently, with Alt pressed to highlight tokens and touchpad panning around the map to view it - can a user accidentally rotate a token instead of panning? If so, that's bad.

**Comment by itamarcu** [comment]
(oops)

**Comment by akrigline** [comment]
You have to have purposefully selected a token for the rotation to work.

**Comment by itamarcu** [comment]
Yes, but the problem was that while holding Alt panning just completely stopped, regardless of whether or not you were selecting or hovering over a token. That was bad (though not what I thought).

For now, I'm fixing this by making multiple modes; Alt can rotate tokens in the "Alternative" mode. Doesn't deactivate token highlighting, might add it later if somebody really wants it.
