### ISSUE TITLE
1.1.0 broke the settings

### ISSUE THREAD

**Issue by mrkwnzl** [itamarcu/ZoomPanOptions#5]
As of the changes in #3, there are no more module settings (the settings don’t appear in Foundry), so that I can’t activate and test the module.

**Comment by itamarcu** [comment]
several things got broken, sorry 😬 

I'll let you know when it's working again. for now, I think (hope) that the module installer still points to the 1.0.0 release

**Comment by akrigline** [comment]
@itamarcu you can double check by opening the foundry.com/admin/packages/packages link and looking at the "package versions" at the bottom of the page. If the manifest URL is "https://raw.githubusercontent.com/itamarcu/ZoomPanOptions/1.0.0/module.json" you're using the release 1.0.0 module.json there.

Then inside the manifest.json, if the `download` is `https://github.com/itamarcu/ZoomPanOptions/archive/1.0.0.zip` it's using the release 1.0.0 zip.

**Comment by akrigline** [comment]
It looks like it's pointing at `master` at the moment but I'm not certain.

**Comment by itamarcu** [comment]
yeah, I didn't consider the fact that I'll be pushing breaking versions all the time while developing.

anyways, I *hope* that everything works now, so feel free to open issues again!

**Comment by itamarcu** [comment]
(version 1.3.3, at least on the surface, looks stable)
